# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.trigger_response import TriggerResponse

class TestTriggerResponse(unittest.TestCase):
    """TriggerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TriggerResponse:
        """Test TriggerResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TriggerResponse`
        """
        model = TriggerResponse()
        if include_optional:
            return TriggerResponse(
                trigger_id = '',
                agent_id = '',
                trigger_type = '',
                provider_id = '',
                name = '',
                description = '',
                is_active = True,
                webhook_url = '',
                created_at = '',
                updated_at = '',
                config = { }
            )
        else:
            return TriggerResponse(
                trigger_id = '',
                agent_id = '',
                trigger_type = '',
                provider_id = '',
                name = '',
                description = '',
                is_active = True,
                webhook_url = '',
                created_at = '',
                updated_at = '',
                config = { },
        )
        """

    def testTriggerResponse(self):
        """Test TriggerResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
