# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.agents_response import AgentsResponse

class TestAgentsResponse(unittest.TestCase):
    """AgentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentsResponse:
        """Test AgentsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentsResponse`
        """
        model = AgentsResponse()
        if include_optional:
            return AgentsResponse(
                agents = [
                    openapi_client.models.agent_response.AgentResponse(
                        agent_id = '', 
                        name = '', 
                        description = '', 
                        system_prompt = '', 
                        configured_mcps = [
                            { }
                            ], 
                        custom_mcps = [
                            { }
                            ], 
                        agentpress_tools = { }, 
                        is_default = True, 
                        profile_image_url = '', 
                        icon_name = '', 
                        icon_color = '', 
                        icon_background = '', 
                        created_at = '', 
                        updated_at = '', 
                        is_public = True, 
                        tags = [
                            ''
                            ], 
                        current_version_id = '', 
                        version_count = 56, 
                        current_version = openapi_client.models.agent_version_response.AgentVersionResponse(
                            version_id = '', 
                            agent_id = '', 
                            version_number = 56, 
                            version_name = '', 
                            system_prompt = '', 
                            model = '', 
                            configured_mcps = [
                                { }
                                ], 
                            custom_mcps = [
                                { }
                                ], 
                            agentpress_tools = { }, 
                            is_active = True, 
                            created_at = '', 
                            updated_at = '', 
                            created_by = '', ), 
                        metadata = { }, )
                    ],
                pagination = openapi_client.models.pagination_info.PaginationInfo(
                    current_page = 56, 
                    page_size = 56, 
                    total_items = 56, 
                    total_pages = 56, 
                    has_next = True, 
                    has_previous = True, )
            )
        else:
            return AgentsResponse(
                agents = [
                    openapi_client.models.agent_response.AgentResponse(
                        agent_id = '', 
                        name = '', 
                        description = '', 
                        system_prompt = '', 
                        configured_mcps = [
                            { }
                            ], 
                        custom_mcps = [
                            { }
                            ], 
                        agentpress_tools = { }, 
                        is_default = True, 
                        profile_image_url = '', 
                        icon_name = '', 
                        icon_color = '', 
                        icon_background = '', 
                        created_at = '', 
                        updated_at = '', 
                        is_public = True, 
                        tags = [
                            ''
                            ], 
                        current_version_id = '', 
                        version_count = 56, 
                        current_version = openapi_client.models.agent_version_response.AgentVersionResponse(
                            version_id = '', 
                            agent_id = '', 
                            version_number = 56, 
                            version_name = '', 
                            system_prompt = '', 
                            model = '', 
                            configured_mcps = [
                                { }
                                ], 
                            custom_mcps = [
                                { }
                                ], 
                            agentpress_tools = { }, 
                            is_active = True, 
                            created_at = '', 
                            updated_at = '', 
                            created_by = '', ), 
                        metadata = { }, )
                    ],
                pagination = openapi_client.models.pagination_info.PaginationInfo(
                    current_page = 56, 
                    page_size = 56, 
                    total_items = 56, 
                    total_pages = 56, 
                    has_next = True, 
                    has_previous = True, ),
        )
        """

    def testAgentsResponse(self):
        """Test AgentsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
