# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.sandbox_api import SandboxApi


class TestSandboxApi(unittest.TestCase):
    """SandboxApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SandboxApi()

    def tearDown(self) -> None:
        pass

    def test_create_file_api_sandboxes_sandbox_id_files_post(self) -> None:
        """Test case for create_file_api_sandboxes_sandbox_id_files_post

        Create File
        """
        pass

    def test_delete_file_api_sandboxes_sandbox_id_files_delete(self) -> None:
        """Test case for delete_file_api_sandboxes_sandbox_id_files_delete

        Delete File
        """
        pass

    def test_delete_sandbox_route_api_sandboxes_sandbox_id_delete(self) -> None:
        """Test case for delete_sandbox_route_api_sandboxes_sandbox_id_delete

        Delete Sandbox Route
        """
        pass

    def test_ensure_project_sandbox_active_api_project_project_id_sandbox_ensure_active_post(self) -> None:
        """Test case for ensure_project_sandbox_active_api_project_project_id_sandbox_ensure_active_post

        Ensure Project Sandbox Active
        """
        pass

    def test_get_sandbox_status_api_sandbox_status_get(self) -> None:
        """Test case for get_sandbox_status_api_sandbox_status_get

        Get Sandbox Status
        """
        pass

    def test_list_files_api_sandboxes_sandbox_id_files_get(self) -> None:
        """Test case for list_files_api_sandboxes_sandbox_id_files_get

        List Files
        """
        pass

    def test_read_file_api_sandboxes_sandbox_id_files_content_get(self) -> None:
        """Test case for read_file_api_sandboxes_sandbox_id_files_content_get

        Read File
        """
        pass

    def test_update_file_api_sandboxes_sandbox_id_files_put(self) -> None:
        """Test case for update_file_api_sandboxes_sandbox_id_files_put

        Update File
        """
        pass


if __name__ == '__main__':
    unittest.main()
