# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.upcoming_run import UpcomingRun

class TestUpcomingRun(unittest.TestCase):
    """UpcomingRun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpcomingRun:
        """Test UpcomingRun
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpcomingRun`
        """
        model = UpcomingRun()
        if include_optional:
            return UpcomingRun(
                trigger_id = '',
                trigger_name = '',
                trigger_type = '',
                next_run_time = '',
                next_run_time_local = '',
                timezone = '',
                cron_expression = '',
                execution_type = '',
                agent_prompt = '',
                workflow_id = '',
                is_active = True,
                human_readable = ''
            )
        else:
            return UpcomingRun(
                trigger_id = '',
                trigger_name = '',
                trigger_type = '',
                next_run_time = '',
                next_run_time_local = '',
                timezone = '',
                cron_expression = '',
                execution_type = '',
                is_active = True,
                human_readable = '',
        )
        """

    def testUpcomingRun(self):
        """Test UpcomingRun"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
