# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.convert_to_docs_response import ConvertToDocsResponse

class TestConvertToDocsResponse(unittest.TestCase):
    """ConvertToDocsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConvertToDocsResponse:
        """Test ConvertToDocsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConvertToDocsResponse`
        """
        model = ConvertToDocsResponse()
        if include_optional:
            return ConvertToDocsResponse(
                success = True,
                message = '',
                docx_url = '',
                google_docs_url = '',
                google_docs_file_id = '',
                is_api_enabled = True
            )
        else:
            return ConvertToDocsResponse(
                success = True,
                message = '',
        )
        """

    def testConvertToDocsResponse(self):
        """Test ConvertToDocsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
