# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.trigger_create_request import TriggerCreateRequest

class TestTriggerCreateRequest(unittest.TestCase):
    """TriggerCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TriggerCreateRequest:
        """Test TriggerCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TriggerCreateRequest`
        """
        model = TriggerCreateRequest()
        if include_optional:
            return TriggerCreateRequest(
                provider_id = '',
                name = '',
                config = { },
                description = ''
            )
        else:
            return TriggerCreateRequest(
                provider_id = '',
                name = '',
                config = { },
        )
        """

    def testTriggerCreateRequest(self):
        """Test TriggerCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
