# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.core_pipedream_api_profile_response import CorePipedreamApiProfileResponse

class TestCorePipedreamApiProfileResponse(unittest.TestCase):
    """CorePipedreamApiProfileResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CorePipedreamApiProfileResponse:
        """Test CorePipedreamApiProfileResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CorePipedreamApiProfileResponse`
        """
        model = CorePipedreamApiProfileResponse()
        if include_optional:
            return CorePipedreamApiProfileResponse(
                profile_id = '',
                account_id = '',
                mcp_qualified_name = '',
                profile_name = '',
                display_name = '',
                app_slug = '',
                app_name = '',
                external_user_id = '',
                enabled_tools = [
                    ''
                    ],
                is_active = True,
                is_default = True,
                is_connected = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_used_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return CorePipedreamApiProfileResponse(
                profile_id = '',
                account_id = '',
                mcp_qualified_name = '',
                profile_name = '',
                display_name = '',
                app_slug = '',
                app_name = '',
                external_user_id = '',
                enabled_tools = [
                    ''
                    ],
                is_active = True,
                is_default = True,
                is_connected = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testCorePipedreamApiProfileResponse(self):
        """Test CorePipedreamApiProfileResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
