# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.grant_credits_request import GrantCreditsRequest

class TestGrantCreditsRequest(unittest.TestCase):
    """GrantCreditsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GrantCreditsRequest:
        """Test GrantCreditsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GrantCreditsRequest`
        """
        model = GrantCreditsRequest()
        if include_optional:
            return GrantCreditsRequest(
                account_ids = [
                    ''
                    ],
                amount = None,
                reason = '',
                is_expiring = True,
                notify_users = True
            )
        else:
            return GrantCreditsRequest(
                account_ids = [
                    ''
                    ],
                amount = None,
                reason = '',
        )
        """

    def testGrantCreditsRequest(self):
        """Test GrantCreditsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
