# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.core_composio_integration_api_profile_response import CoreComposioIntegrationApiProfileResponse

class TestCoreComposioIntegrationApiProfileResponse(unittest.TestCase):
    """CoreComposioIntegrationApiProfileResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoreComposioIntegrationApiProfileResponse:
        """Test CoreComposioIntegrationApiProfileResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoreComposioIntegrationApiProfileResponse`
        """
        model = CoreComposioIntegrationApiProfileResponse()
        if include_optional:
            return CoreComposioIntegrationApiProfileResponse(
                profile_id = '',
                profile_name = '',
                display_name = '',
                toolkit_slug = '',
                toolkit_name = '',
                mcp_url = '',
                redirect_url = '',
                connected_account_id = '',
                is_connected = True,
                is_default = True,
                created_at = ''
            )
        else:
            return CoreComposioIntegrationApiProfileResponse(
                profile_id = '',
                profile_name = '',
                display_name = '',
                toolkit_slug = '',
                toolkit_name = '',
                mcp_url = '',
                is_connected = True,
                is_default = True,
                created_at = '',
        )
        """

    def testCoreComposioIntegrationApiProfileResponse(self):
        """Test CoreComposioIntegrationApiProfileResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
