# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.refund_request import RefundRequest

class TestRefundRequest(unittest.TestCase):
    """RefundRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefundRequest:
        """Test RefundRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefundRequest`
        """
        model = RefundRequest()
        if include_optional:
            return RefundRequest(
                account_id = '',
                amount = None,
                reason = '',
                is_expiring = True,
                stripe_refund = True,
                payment_intent_id = ''
            )
        else:
            return RefundRequest(
                account_id = '',
                amount = None,
                reason = '',
        )
        """

    def testRefundRequest(self):
        """Test RefundRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
