# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.auth_url_response import AuthURLResponse

class TestAuthURLResponse(unittest.TestCase):
    """AuthURLResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthURLResponse:
        """Test AuthURLResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthURLResponse`
        """
        model = AuthURLResponse()
        if include_optional:
            return AuthURLResponse(
                auth_url = '',
                message = ''
            )
        else:
            return AuthURLResponse(
                auth_url = '',
                message = '',
        )
        """

    def testAuthURLResponse(self):
        """Test AuthURLResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
