# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workflow_update_request import WorkflowUpdateRequest

class TestWorkflowUpdateRequest(unittest.TestCase):
    """WorkflowUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowUpdateRequest:
        """Test WorkflowUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowUpdateRequest`
        """
        model = WorkflowUpdateRequest()
        if include_optional:
            return WorkflowUpdateRequest(
                name = '',
                description = '',
                trigger_phrase = '',
                is_default = True,
                status = '',
                steps = [
                    openapi_client.models.workflow_step_request.WorkflowStepRequest(
                        id = '', 
                        name = '', 
                        description = '', 
                        type = '', 
                        config = { }, 
                        conditions = { }, 
                        order = 56, 
                        parent_conditional_id = '', 
                        children = [
                            openapi_client.models.workflow_step_request.WorkflowStepRequest(
                                id = '', 
                                name = '', 
                                description = '', 
                                type = '', 
                                config = { }, 
                                order = 56, 
                                parent_conditional_id = '', )
                            ], )
                    ]
            )
        else:
            return WorkflowUpdateRequest(
        )
        """

    def testWorkflowUpdateRequest(self):
        """Test WorkflowUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
