# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.installation_response import InstallationResponse

class TestInstallationResponse(unittest.TestCase):
    """InstallationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstallationResponse:
        """Test InstallationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstallationResponse`
        """
        model = InstallationResponse()
        if include_optional:
            return InstallationResponse(
                status = '',
                instance_id = '',
                name = '',
                missing_regular_credentials = [
                    { }
                    ],
                missing_custom_configs = [
                    { }
                    ],
                template_info = { }
            )
        else:
            return InstallationResponse(
                status = '',
        )
        """

    def testInstallationResponse(self):
        """Test InstallationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
