# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.composio_toolkit_group import ComposioToolkitGroup

class TestComposioToolkitGroup(unittest.TestCase):
    """ComposioToolkitGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComposioToolkitGroup:
        """Test ComposioToolkitGroup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComposioToolkitGroup`
        """
        model = ComposioToolkitGroup()
        if include_optional:
            return ComposioToolkitGroup(
                toolkit_slug = '',
                toolkit_name = '',
                icon_url = '',
                profiles = [
                    openapi_client.models.composio_profile_summary.ComposioProfileSummary(
                        profile_id = '', 
                        profile_name = '', 
                        display_name = '', 
                        toolkit_slug = '', 
                        toolkit_name = '', 
                        is_connected = True, 
                        is_default = True, 
                        created_at = '', 
                        has_mcp_url = True, )
                    ]
            )
        else:
            return ComposioToolkitGroup(
                toolkit_slug = '',
                toolkit_name = '',
                profiles = [
                    openapi_client.models.composio_profile_summary.ComposioProfileSummary(
                        profile_id = '', 
                        profile_name = '', 
                        display_name = '', 
                        toolkit_slug = '', 
                        toolkit_name = '', 
                        is_connected = True, 
                        is_default = True, 
                        created_at = '', 
                        has_mcp_url = True, )
                    ],
        )
        """

    def testComposioToolkitGroup(self):
        """Test ComposioToolkitGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
