# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.mcp_connection_request import MCPConnectionRequest

class TestMCPConnectionRequest(unittest.TestCase):
    """MCPConnectionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MCPConnectionRequest:
        """Test MCPConnectionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MCPConnectionRequest`
        """
        model = MCPConnectionRequest()
        if include_optional:
            return MCPConnectionRequest(
                app_slug = '',
                oauth_app_id = ''
            )
        else:
            return MCPConnectionRequest(
                app_slug = '',
        )
        """

    def testMCPConnectionRequest(self):
        """Test MCPConnectionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
