# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.document_tools_api import DocumentToolsApi


class TestDocumentToolsApi(unittest.TestCase):
    """DocumentToolsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentToolsApi()

    def tearDown(self) -> None:
        pass

    def test_convert_and_upload_to_google_docs_api_document_tools_convert_and_upload_to_docs_post(self) -> None:
        """Test case for convert_and_upload_to_google_docs_api_document_tools_convert_and_upload_to_docs_post

        Convert And Upload To Google Docs
        """
        pass

    def test_debug_endpoint_api_document_tools_debug_get(self) -> None:
        """Test case for debug_endpoint_api_document_tools_debug_get

        Debug Endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
