# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_activate_version_api_agents_agent_id_versions_version_id_activate_put(self) -> None:
        """Test case for activate_version_api_agents_agent_id_versions_version_id_activate_put

        Activate Version
        """
        pass

    def test_add_message_to_thread_api_threads_thread_id_messages_add_post(self) -> None:
        """Test case for add_message_to_thread_api_threads_thread_id_messages_add_post

        Add Message To Thread
        """
        pass

    def test_analyze_json_for_import_api_agents_json_analyze_post(self) -> None:
        """Test case for analyze_json_for_import_api_agents_json_analyze_post

        Analyze Json For Import
        """
        pass

    def test_bulk_delete_credential_profiles_api_secure_mcp_credential_profiles_bulk_delete_post(self) -> None:
        """Test case for bulk_delete_credential_profiles_api_secure_mcp_credential_profiles_bulk_delete_post

        Bulk Delete Credential Profiles
        """
        pass

    def test_compare_versions_api_agents_agent_id_versions_version1_id_compare_version2_id_get(self) -> None:
        """Test case for compare_versions_api_agents_agent_id_versions_version1_id_compare_version2_id_get

        Compare Versions
        """
        pass

    def test_create_agent_api_agents_post(self) -> None:
        """Test case for create_agent_api_agents_post

        Create Agent
        """
        pass

    def test_create_api_key_api_api_keys_post(self) -> None:
        """Test case for create_api_key_api_api_keys_post

        Create Api Key
        """
        pass

    def test_create_message_api_threads_thread_id_messages_post(self) -> None:
        """Test case for create_message_api_threads_thread_id_messages_post

        Create Message
        """
        pass

    def test_create_template_from_agent_api_templates_post(self) -> None:
        """Test case for create_template_from_agent_api_templates_post

        Create Template From Agent
        """
        pass

    def test_create_thread_api_threads_post(self) -> None:
        """Test case for create_thread_api_threads_post

        Create Thread
        """
        pass

    def test_create_version_api_agents_agent_id_versions_post(self) -> None:
        """Test case for create_version_api_agents_agent_id_versions_post

        Create Version
        """
        pass

    def test_delete_agent_api_agents_agent_id_delete(self) -> None:
        """Test case for delete_agent_api_agents_agent_id_delete

        Delete Agent
        """
        pass

    def test_delete_api_key_api_api_keys_key_id_delete(self) -> None:
        """Test case for delete_api_key_api_api_keys_key_id_delete

        Delete Api Key
        """
        pass

    def test_delete_credential_api_secure_mcp_credentials_mcp_qualified_name_delete(self) -> None:
        """Test case for delete_credential_api_secure_mcp_credentials_mcp_qualified_name_delete

        Delete Credential
        """
        pass

    def test_delete_credential_profile_api_secure_mcp_credential_profiles_profile_id_delete(self) -> None:
        """Test case for delete_credential_profile_api_secure_mcp_credential_profiles_profile_id_delete

        Delete Credential Profile
        """
        pass

    def test_delete_message_api_threads_thread_id_messages_message_id_delete(self) -> None:
        """Test case for delete_message_api_threads_thread_id_messages_message_id_delete

        Delete Message
        """
        pass

    def test_delete_template_api_templates_template_id_delete(self) -> None:
        """Test case for delete_template_api_templates_template_id_delete

        Delete Template
        """
        pass

    def test_discover_custom_mcp_tools_api_mcp_discover_custom_tools_post(self) -> None:
        """Test case for discover_custom_mcp_tools_api_mcp_discover_custom_tools_post

        Discover Custom Mcp Tools
        """
        pass

    def test_export_agent_api_agents_agent_id_export_get(self) -> None:
        """Test case for export_agent_api_agents_agent_id_export_get

        Export Agent
        """
        pass

    def test_generate_agent_icon_api_agents_generate_icon_post(self) -> None:
        """Test case for generate_agent_icon_api_agents_generate_icon_post

        Generate Agent Icon
        """
        pass

    def test_get_agent_api_agents_agent_id_get(self) -> None:
        """Test case for get_agent_api_agents_agent_id_get

        Get Agent
        """
        pass

    def test_get_agent_run_api_agent_run_agent_run_id_get(self) -> None:
        """Test case for get_agent_run_api_agent_run_agent_run_id_get

        Get Agent Run
        """
        pass

    def test_get_agent_run_api_agent_runs_agent_run_id_get(self) -> None:
        """Test case for get_agent_run_api_agent_runs_agent_run_id_get

        Get Agent Run
        """
        pass

    def test_get_agent_runs_api_thread_thread_id_agent_runs_get(self) -> None:
        """Test case for get_agent_runs_api_thread_thread_id_agent_runs_get

        Get Agent Runs
        """
        pass

    def test_get_agent_tools_api_agents_agent_id_tools_get(self) -> None:
        """Test case for get_agent_tools_api_agents_agent_id_tools_get

        Get Agent Tools
        """
        pass

    def test_get_agents_api_agents_get(self) -> None:
        """Test case for get_agents_api_agents_get

        Get Agents
        """
        pass

    def test_get_composio_mcp_url_api_secure_mcp_composio_profiles_profile_id_mcp_url_get(self) -> None:
        """Test case for get_composio_mcp_url_api_secure_mcp_composio_profiles_profile_id_mcp_url_get

        Get Composio Mcp Url
        """
        pass

    def test_get_composio_profiles_api_secure_mcp_composio_profiles_get(self) -> None:
        """Test case for get_composio_profiles_api_secure_mcp_composio_profiles_get

        Get Composio Profiles
        """
        pass

    def test_get_credential_profile_api_secure_mcp_credential_profiles_profile_profile_id_get(self) -> None:
        """Test case for get_credential_profile_api_secure_mcp_credential_profiles_profile_profile_id_get

        Get Credential Profile
        """
        pass

    def test_get_credential_profiles_for_mcp_api_secure_mcp_credential_profiles_mcp_qualified_name_get(self) -> None:
        """Test case for get_credential_profiles_for_mcp_api_secure_mcp_credential_profiles_mcp_qualified_name_get

        Get Credential Profiles For Mcp
        """
        pass

    def test_get_custom_mcp_tools_for_agent_api_agents_agent_id_custom_mcp_tools_get(self) -> None:
        """Test case for get_custom_mcp_tools_for_agent_api_agents_agent_id_custom_mcp_tools_get

        Get Custom Mcp Tools For Agent
        """
        pass

    def test_get_marketplace_templates_api_templates_marketplace_get(self) -> None:
        """Test case for get_marketplace_templates_api_templates_marketplace_get

        Get Marketplace Templates
        """
        pass

    def test_get_my_templates_api_templates_my_get(self) -> None:
        """Test case for get_my_templates_api_templates_my_get

        Get My Templates
        """
        pass

    def test_get_public_template_api_templates_public_template_id_get(self) -> None:
        """Test case for get_public_template_api_templates_public_template_id_get

        Get Public Template
        """
        pass

    def test_get_template_api_templates_template_id_get(self) -> None:
        """Test case for get_template_api_templates_template_id_get

        Get Template
        """
        pass

    def test_get_thread_agent_api_thread_thread_id_agent_get(self) -> None:
        """Test case for get_thread_agent_api_thread_thread_id_agent_get

        Get Thread Agent
        """
        pass

    def test_get_thread_api_threads_thread_id_get(self) -> None:
        """Test case for get_thread_api_threads_thread_id_get

        Get Thread
        """
        pass

    def test_get_thread_messages_api_threads_thread_id_messages_get(self) -> None:
        """Test case for get_thread_messages_api_threads_thread_id_messages_get

        Get Thread Messages
        """
        pass

    def test_get_user_credential_profiles_api_secure_mcp_credential_profiles_get(self) -> None:
        """Test case for get_user_credential_profiles_api_secure_mcp_credential_profiles_get

        Get User Credential Profiles
        """
        pass

    def test_get_user_credentials_api_secure_mcp_credentials_get(self) -> None:
        """Test case for get_user_credentials_api_secure_mcp_credentials_get

        Get User Credentials
        """
        pass

    def test_get_user_threads_api_threads_get(self) -> None:
        """Test case for get_user_threads_api_threads_get

        Get User Threads
        """
        pass

    def test_get_version_api_agents_agent_id_versions_version_id_get(self) -> None:
        """Test case for get_version_api_agents_agent_id_versions_version_id_get

        Get Version
        """
        pass

    def test_get_versions_api_agents_agent_id_versions_get(self) -> None:
        """Test case for get_versions_api_agents_agent_id_versions_get

        Get Versions
        """
        pass

    def test_health_check_api_health_docker_get(self) -> None:
        """Test case for health_check_api_health_docker_get

        Health Check
        """
        pass

    def test_health_check_api_health_get(self) -> None:
        """Test case for health_check_api_health_get

        Health Check
        """
        pass

    def test_import_agent_from_json_api_agents_json_import_post(self) -> None:
        """Test case for import_agent_from_json_api_agents_json_import_post

        Import Agent From Json
        """
        pass

    def test_initiate_agent_with_files_api_agent_initiate_post(self) -> None:
        """Test case for initiate_agent_with_files_api_agent_initiate_post

        Initiate Agent With Files
        """
        pass

    def test_install_template_api_templates_install_post(self) -> None:
        """Test case for install_template_api_templates_install_post

        Install Template
        """
        pass

    def test_list_api_keys_api_api_keys_get(self) -> None:
        """Test case for list_api_keys_api_api_keys_get

        List Api Keys
        """
        pass

    def test_publish_template_api_templates_template_id_publish_post(self) -> None:
        """Test case for publish_template_api_templates_template_id_publish_post

        Publish Template
        """
        pass

    def test_revoke_api_key_api_api_keys_key_id_revoke_patch(self) -> None:
        """Test case for revoke_api_key_api_api_keys_key_id_revoke_patch

        Revoke Api Key
        """
        pass

    def test_rollback_to_version_api_agents_agent_id_versions_version_id_rollback_post(self) -> None:
        """Test case for rollback_to_version_api_agents_agent_id_versions_version_id_rollback_post

        Rollback To Version
        """
        pass

    def test_send_welcome_email_api_send_welcome_email_post(self) -> None:
        """Test case for send_welcome_email_api_send_welcome_email_post

        Send Welcome Email
        """
        pass

    def test_set_default_credential_profile_api_secure_mcp_credential_profiles_profile_id_set_default_put(self) -> None:
        """Test case for set_default_credential_profile_api_secure_mcp_credential_profiles_profile_id_set_default_put

        Set Default Credential Profile
        """
        pass

    def test_start_agent_api_thread_thread_id_agent_start_post(self) -> None:
        """Test case for start_agent_api_thread_thread_id_agent_start_post

        Start Agent
        """
        pass

    def test_stop_agent_api_agent_run_agent_run_id_stop_post(self) -> None:
        """Test case for stop_agent_api_agent_run_agent_run_id_stop_post

        Stop Agent
        """
        pass

    def test_store_credential_api_secure_mcp_credentials_post(self) -> None:
        """Test case for store_credential_api_secure_mcp_credentials_post

        Store Credential
        """
        pass

    def test_store_credential_profile_api_secure_mcp_credential_profiles_post(self) -> None:
        """Test case for store_credential_profile_api_secure_mcp_credential_profiles_post

        Store Credential Profile
        """
        pass

    def test_stream_agent_run_api_agent_run_agent_run_id_stream_get(self) -> None:
        """Test case for stream_agent_run_api_agent_run_agent_run_id_stream_get

        Stream Agent Run
        """
        pass

    def test_unpublish_template_api_templates_template_id_unpublish_post(self) -> None:
        """Test case for unpublish_template_api_templates_template_id_unpublish_post

        Unpublish Template
        """
        pass

    def test_update_agent_api_agents_agent_id_put(self) -> None:
        """Test case for update_agent_api_agents_agent_id_put

        Update Agent
        """
        pass

    def test_update_agent_custom_mcps_api_agents_agent_id_custom_mcp_tools_put(self) -> None:
        """Test case for update_agent_custom_mcps_api_agents_agent_id_custom_mcp_tools_put

        Update Agent Custom Mcps
        """
        pass

    def test_update_custom_mcp_tools_for_agent_api_agents_agent_id_custom_mcp_tools_post(self) -> None:
        """Test case for update_custom_mcp_tools_for_agent_api_agents_agent_id_custom_mcp_tools_post

        Update Custom Mcp Tools For Agent
        """
        pass

    def test_update_version_details_api_agents_agent_id_versions_version_id_details_put(self) -> None:
        """Test case for update_version_details_api_agents_agent_id_versions_version_id_details_put

        Update Version Details
        """
        pass


if __name__ == '__main__':
    unittest.main()
