# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.integration_status_response import IntegrationStatusResponse

class TestIntegrationStatusResponse(unittest.TestCase):
    """IntegrationStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntegrationStatusResponse:
        """Test IntegrationStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntegrationStatusResponse`
        """
        model = IntegrationStatusResponse()
        if include_optional:
            return IntegrationStatusResponse(
                status = '',
                toolkit = '',
                auth_config_id = '',
                connected_account_id = '',
                mcp_server_id = '',
                final_mcp_url = '',
                profile_id = '',
                redirect_url = ''
            )
        else:
            return IntegrationStatusResponse(
                status = '',
                toolkit = '',
                auth_config_id = '',
                connected_account_id = '',
                mcp_server_id = '',
                final_mcp_url = '',
        )
        """

    def testIntegrationStatusResponse(self):
        """Test IntegrationStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
