# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.agent_create_request import AgentCreateRequest

class TestAgentCreateRequest(unittest.TestCase):
    """AgentCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentCreateRequest:
        """Test AgentCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentCreateRequest`
        """
        model = AgentCreateRequest()
        if include_optional:
            return AgentCreateRequest(
                name = '',
                description = '',
                system_prompt = '',
                configured_mcps = [
                    { }
                    ],
                custom_mcps = [
                    { }
                    ],
                agentpress_tools = { },
                is_default = True,
                profile_image_url = '',
                icon_name = '',
                icon_color = '',
                icon_background = ''
            )
        else:
            return AgentCreateRequest(
                name = '',
        )
        """

    def testAgentCreateRequest(self):
        """Test AgentCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
