# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pagination_meta import PaginationMeta

class TestPaginationMeta(unittest.TestCase):
    """PaginationMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginationMeta:
        """Test PaginationMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginationMeta`
        """
        model = PaginationMeta()
        if include_optional:
            return PaginationMeta(
                current_page = 56,
                page_size = 56,
                total_items = 56,
                total_pages = 56,
                has_next = True,
                has_previous = True,
                next_cursor = '',
                previous_cursor = ''
            )
        else:
            return PaginationMeta(
                current_page = 56,
                page_size = 56,
                total_items = 56,
                total_pages = 56,
                has_next = True,
                has_previous = True,
        )
        """

    def testPaginationMeta(self):
        """Test PaginationMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
