# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.knowledge_base_entry_response import KnowledgeBaseEntryResponse

class TestKnowledgeBaseEntryResponse(unittest.TestCase):
    """KnowledgeBaseEntryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KnowledgeBaseEntryResponse:
        """Test KnowledgeBaseEntryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KnowledgeBaseEntryResponse`
        """
        model = KnowledgeBaseEntryResponse()
        if include_optional:
            return KnowledgeBaseEntryResponse(
                entry_id = '',
                name = '',
                description = '',
                content = '',
                usage_context = '',
                is_active = True,
                content_tokens = 56,
                created_at = '',
                updated_at = '',
                source_type = '',
                source_metadata = { },
                file_size = 56,
                file_mime_type = ''
            )
        else:
            return KnowledgeBaseEntryResponse(
                entry_id = '',
                name = '',
                description = '',
                content = '',
                usage_context = '',
                is_active = True,
                content_tokens = 56,
                created_at = '',
                updated_at = '',
        )
        """

    def testKnowledgeBaseEntryResponse(self):
        """Test KnowledgeBaseEntryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
