# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.version_comparison_response import VersionComparisonResponse

class TestVersionComparisonResponse(unittest.TestCase):
    """VersionComparisonResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VersionComparisonResponse:
        """Test VersionComparisonResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VersionComparisonResponse`
        """
        model = VersionComparisonResponse()
        if include_optional:
            return VersionComparisonResponse(
                version1 = openapi_client.models.version_response.VersionResponse(
                    version_id = '', 
                    agent_id = '', 
                    version_number = 56, 
                    version_name = '', 
                    system_prompt = '', 
                    model = '', 
                    configured_mcps = [
                        { }
                        ], 
                    custom_mcps = [
                        { }
                        ], 
                    agentpress_tools = { }, 
                    is_active = True, 
                    status = '', 
                    created_at = '', 
                    updated_at = '', 
                    created_by = '', 
                    change_description = '', 
                    previous_version_id = '', ),
                version2 = openapi_client.models.version_response.VersionResponse(
                    version_id = '', 
                    agent_id = '', 
                    version_number = 56, 
                    version_name = '', 
                    system_prompt = '', 
                    model = '', 
                    configured_mcps = [
                        { }
                        ], 
                    custom_mcps = [
                        { }
                        ], 
                    agentpress_tools = { }, 
                    is_active = True, 
                    status = '', 
                    created_at = '', 
                    updated_at = '', 
                    created_by = '', 
                    change_description = '', 
                    previous_version_id = '', ),
                differences = [
                    { }
                    ]
            )
        else:
            return VersionComparisonResponse(
                version1 = openapi_client.models.version_response.VersionResponse(
                    version_id = '', 
                    agent_id = '', 
                    version_number = 56, 
                    version_name = '', 
                    system_prompt = '', 
                    model = '', 
                    configured_mcps = [
                        { }
                        ], 
                    custom_mcps = [
                        { }
                        ], 
                    agentpress_tools = { }, 
                    is_active = True, 
                    status = '', 
                    created_at = '', 
                    updated_at = '', 
                    created_by = '', 
                    change_description = '', 
                    previous_version_id = '', ),
                version2 = openapi_client.models.version_response.VersionResponse(
                    version_id = '', 
                    agent_id = '', 
                    version_number = 56, 
                    version_name = '', 
                    system_prompt = '', 
                    model = '', 
                    configured_mcps = [
                        { }
                        ], 
                    custom_mcps = [
                        { }
                        ], 
                    agentpress_tools = { }, 
                    is_active = True, 
                    status = '', 
                    created_at = '', 
                    updated_at = '', 
                    created_by = '', 
                    change_description = '', 
                    previous_version_id = '', ),
                differences = [
                    { }
                    ],
        )
        """

    def testVersionComparisonResponse(self):
        """Test VersionComparisonResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
