# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_checkout_session_request import CreateCheckoutSessionRequest

class TestCreateCheckoutSessionRequest(unittest.TestCase):
    """CreateCheckoutSessionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCheckoutSessionRequest:
        """Test CreateCheckoutSessionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCheckoutSessionRequest`
        """
        model = CreateCheckoutSessionRequest()
        if include_optional:
            return CreateCheckoutSessionRequest(
                price_id = '',
                success_url = '',
                cancel_url = ''
            )
        else:
            return CreateCheckoutSessionRequest(
                price_id = '',
                success_url = '',
                cancel_url = '',
        )
        """

    def testCreateCheckoutSessionRequest(self):
        """Test CreateCheckoutSessionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
