# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pagination_info import PaginationInfo

class TestPaginationInfo(unittest.TestCase):
    """PaginationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginationInfo:
        """Test PaginationInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginationInfo`
        """
        model = PaginationInfo()
        if include_optional:
            return PaginationInfo(
                current_page = 56,
                page_size = 56,
                total_items = 56,
                total_pages = 56,
                has_next = True,
                has_previous = True
            )
        else:
            return PaginationInfo(
                current_page = 56,
                page_size = 56,
                total_items = 56,
                total_pages = 56,
                has_next = True,
                has_previous = True,
        )
        """

    def testPaginationInfo(self):
        """Test PaginationInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
