# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.processing_job_response import ProcessingJobResponse

class TestProcessingJobResponse(unittest.TestCase):
    """ProcessingJobResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessingJobResponse:
        """Test ProcessingJobResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessingJobResponse`
        """
        model = ProcessingJobResponse()
        if include_optional:
            return ProcessingJobResponse(
                job_id = '',
                job_type = '',
                status = '',
                source_info = { },
                result_info = { },
                entries_created = 56,
                total_files = 56,
                created_at = '',
                completed_at = '',
                error_message = ''
            )
        else:
            return ProcessingJobResponse(
                job_id = '',
                job_type = '',
                status = '',
                source_info = { },
                result_info = { },
                entries_created = 56,
                total_files = 56,
                created_at = '',
                completed_at = '',
                error_message = '',
        )
        """

    def testProcessingJobResponse(self):
        """Test ProcessingJobResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
