# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.agent_version_response import AgentVersionResponse

class TestAgentVersionResponse(unittest.TestCase):
    """AgentVersionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentVersionResponse:
        """Test AgentVersionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentVersionResponse`
        """
        model = AgentVersionResponse()
        if include_optional:
            return AgentVersionResponse(
                version_id = '',
                agent_id = '',
                version_number = 56,
                version_name = '',
                system_prompt = '',
                model = '',
                configured_mcps = [
                    { }
                    ],
                custom_mcps = [
                    { }
                    ],
                agentpress_tools = { },
                is_active = True,
                created_at = '',
                updated_at = '',
                created_by = ''
            )
        else:
            return AgentVersionResponse(
                version_id = '',
                agent_id = '',
                version_number = 56,
                version_name = '',
                system_prompt = '',
                configured_mcps = [
                    { }
                    ],
                custom_mcps = [
                    { }
                    ],
                agentpress_tools = { },
                is_active = True,
                created_at = '',
                updated_at = '',
        )
        """

    def testAgentVersionResponse(self):
        """Test AgentVersionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
