# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()

    def tearDown(self) -> None:
        pass

    def test_admin_install_suna_for_user_api_admin_suna_agents_install_user_account_id_post(self) -> None:
        """Test case for admin_install_suna_for_user_api_admin_suna_agents_install_user_account_id_post

        Admin Install Suna For User
        """
        pass

    def test_get_env_vars_api_admin_env_vars_get(self) -> None:
        """Test case for get_env_vars_api_admin_env_vars_get

        Get Env Vars
        """
        pass

    def test_save_env_vars_api_admin_env_vars_post(self) -> None:
        """Test case for save_env_vars_api_admin_env_vars_post

        Save Env Vars
        """
        pass


if __name__ == '__main__':
    unittest.main()
