# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.paginated_response_dict_str_any import PaginatedResponseDictStrAny

class TestPaginatedResponseDictStrAny(unittest.TestCase):
    """PaginatedResponseDictStrAny unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedResponseDictStrAny:
        """Test PaginatedResponseDictStrAny
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedResponseDictStrAny`
        """
        model = PaginatedResponseDictStrAny()
        if include_optional:
            return PaginatedResponseDictStrAny(
                data = [
                    { }
                    ],
                pagination = openapi_client.models.pagination_meta.PaginationMeta(
                    current_page = 56, 
                    page_size = 56, 
                    total_items = 56, 
                    total_pages = 56, 
                    has_next = True, 
                    has_previous = True, 
                    next_cursor = '', 
                    previous_cursor = '', )
            )
        else:
            return PaginatedResponseDictStrAny(
                data = [
                    { }
                    ],
                pagination = openapi_client.models.pagination_meta.PaginationMeta(
                    current_page = 56, 
                    page_size = 56, 
                    total_items = 56, 
                    total_pages = 56, 
                    has_next = True, 
                    has_previous = True, 
                    next_cursor = '', 
                    previous_cursor = '', ),
        )
        """

    def testPaginatedResponseDictStrAny(self):
        """Test PaginatedResponseDictStrAny"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
