# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ConvertToDocsResponse(BaseModel):
    """
    ConvertToDocsResponse
    """ # noqa: E501
    success: StrictBool = Field(description="Whether the conversion was successful")
    message: StrictStr = Field(description="Status message")
    docx_url: Optional[StrictStr] = None
    google_docs_url: Optional[StrictStr] = None
    google_docs_file_id: Optional[StrictStr] = None
    is_api_enabled: Optional[StrictBool] = Field(default=True, description="Whether Google API is enabled")
    __properties: ClassVar[List[str]] = ["success", "message", "docx_url", "google_docs_url", "google_docs_file_id", "is_api_enabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConvertToDocsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if docx_url (nullable) is None
        # and model_fields_set contains the field
        if self.docx_url is None and "docx_url" in self.model_fields_set:
            _dict['docx_url'] = None

        # set to None if google_docs_url (nullable) is None
        # and model_fields_set contains the field
        if self.google_docs_url is None and "google_docs_url" in self.model_fields_set:
            _dict['google_docs_url'] = None

        # set to None if google_docs_file_id (nullable) is None
        # and model_fields_set contains the field
        if self.google_docs_file_id is None and "google_docs_file_id" in self.model_fields_set:
            _dict['google_docs_file_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConvertToDocsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "message": obj.get("message"),
            "docx_url": obj.get("docx_url"),
            "google_docs_url": obj.get("google_docs_url"),
            "google_docs_file_id": obj.get("google_docs_file_id"),
            "is_api_enabled": obj.get("is_api_enabled") if obj.get("is_api_enabled") is not None else True
        })
        return _obj


