# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TriggerResponse(BaseModel):
    """
    TriggerResponse
    """ # noqa: E501
    trigger_id: StrictStr
    agent_id: StrictStr
    trigger_type: StrictStr
    provider_id: StrictStr
    name: StrictStr
    description: Optional[StrictStr]
    is_active: StrictBool
    webhook_url: Optional[StrictStr]
    created_at: StrictStr
    updated_at: StrictStr
    config: Dict[str, Any]
    __properties: ClassVar[List[str]] = ["trigger_id", "agent_id", "trigger_type", "provider_id", "name", "description", "is_active", "webhook_url", "created_at", "updated_at", "config"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TriggerResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if webhook_url (nullable) is None
        # and model_fields_set contains the field
        if self.webhook_url is None and "webhook_url" in self.model_fields_set:
            _dict['webhook_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TriggerResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "trigger_id": obj.get("trigger_id"),
            "agent_id": obj.get("agent_id"),
            "trigger_type": obj.get("trigger_type"),
            "provider_id": obj.get("provider_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "is_active": obj.get("is_active"),
            "webhook_url": obj.get("webhook_url"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "config": obj.get("config")
        })
        return _obj


